version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    networks:
      - app-tier
    environment:
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9042:9042"
  load:
    build:
      context: ./load
    image: "load:latest"
    networks:
      - app-tier
    ports:
      - "8082:8082"
    depends_on:
      cassandra:
        condition: service_healthy
  save:
    build:
      context: ./save
    image: "save:latest"
    networks:
      - app-tier
    ports:
      - "8081:8081"
    depends_on:
      load:
        condition: service_started