spring:
  application:
    name: save
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: badword-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
